//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace Diten.Web.UI.Apps.Templates.TestApp {
    
    
    public partial class TestTemplate {
        
        /// <summary>
        /// DesktopModuleProxy control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Ext.Net.DesktopModuleProxy DesktopModuleProxy;
        
        /// <summary>
        /// Window control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Diten.Web.UI.WebControls.Window Window;
        
        /// <summary>
        /// Toolbar control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Diten.Web.UI.WebControls.Toolbar Toolbar;
        
        /// <summary>
        /// TabPanel control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Diten.Web.UI.WebControls.TabPanel TabPanel;
        
        /// <summary>
        /// PanelHome control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Diten.Web.UI.WebControls.Panel PanelHome;
        
        /// <summary>
        /// PanelHomeToolbar control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Diten.Web.UI.WebControls.Toolbar PanelHomeToolbar;
        
        /// <summary>
        /// ButtonGroupHelp control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Diten.Web.UI.WebControls.ButtonGroup ButtonGroupHelp;
        
        /// <summary>
        /// ButtonGroupHelpMenuSeparator control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Ext.Net.MenuSeparator ButtonGroupHelpMenuSeparator;
        
        /// <summary>
        /// ButtonHelp control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Diten.Web.UI.WebControls.SplitButton ButtonHelp;
        
        /// <summary>
        /// HelpMenu control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Ext.Net.Menu HelpMenu;
        
        /// <summary>
        /// MenuItemAboutDiten control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Ext.Net.MenuItem MenuItemAboutDiten;
        
        /// <summary>
        /// ContentPanel control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Diten.Web.UI.WebControls.Panel ContentPanel;
        
        /// <summary>
        /// NorthPanel control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Diten.Web.UI.WebControls.Panel NorthPanel;
        
        /// <summary>
        /// WestPanel control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Diten.Web.UI.WebControls.Panel WestPanel;
        
        /// <summary>
        /// CenterPanel control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Diten.Web.UI.WebControls.Panel CenterPanel;
        
        /// <summary>
        /// EastPanel control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Diten.Web.UI.WebControls.Panel EastPanel;
        
        /// <summary>
        /// StatusForm control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Ext.Net.FormPanel StatusForm;
        
        /// <summary>
        /// SouthPanel control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Diten.Web.UI.WebControls.Panel SouthPanel;
        
        /// <summary>
        /// StatusBar control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Ext.Net.StatusBar StatusBar;
        
        /// <summary>
        /// wordCount control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Ext.Net.ToolbarTextItem wordCount;
        
        /// <summary>
        /// charCount control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Ext.Net.ToolbarTextItem charCount;
        
        /// <summary>
        /// clock control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Ext.Net.ToolbarTextItem clock;
        
        /// <summary>
        /// ButtonViewDetail control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Diten.Web.UI.WebControls.Button ButtonViewDetail;
        
        /// <summary>
        /// ButtonViewIcons control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Diten.Web.UI.WebControls.Button ButtonViewIcons;
    }
}
