//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace Diten.Web.UI.Apps.Templates.Application {
    
    
    public partial class ApplicationTemplate {
        
        /// <summary>
        /// Toolbar control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Diten.Web.UI.WebControls.Toolbar Toolbar;
        
        /// <summary>
        /// TabPanelHolder control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Diten.Web.UI.WebControls.TabPanel TabPanelHolder;
        
        /// <summary>
        /// PanelHome control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Diten.Web.UI.WebControls.Panel PanelHome;
        
        /// <summary>
        /// ToolbarHome control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Diten.Web.UI.WebControls.ToolbarHome ToolbarHome;
        
        /// <summary>
        /// PanelShare control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Diten.Web.UI.WebControls.Panel PanelShare;
        
        /// <summary>
        /// ToolbarShare control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Diten.Web.UI.WebControls.ToolbarShare ToolbarShare;
        
        /// <summary>
        /// PanelJobs control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Diten.Web.UI.WebControls.Panel PanelJobs;
        
        /// <summary>
        /// ButtonGroupServerJobs control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Diten.Web.UI.WebControls.ButtonGroup ButtonGroupServerJobs;
        
        /// <summary>
        /// StatsButtonSetOdbcLogging control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Diten.Web.UI.WebControls.Button StatsButtonSetOdbcLogging;
        
        /// <summary>
        /// StatsButton2 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Diten.Web.UI.WebControls.Button StatsButton2;
        
        /// <summary>
        /// StatsButton3 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Diten.Web.UI.WebControls.Button StatsButton3;
        
        /// <summary>
        /// StatsButton4 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Diten.Web.UI.WebControls.Button StatsButton4;
        
        /// <summary>
        /// StatsButton5 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Diten.Web.UI.WebControls.Button StatsButton5;
        
        /// <summary>
        /// StatsButton6 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Diten.Web.UI.WebControls.Button StatsButton6;
        
        /// <summary>
        /// ButtonTest control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Ext.Net.Button ButtonTest;
        
        /// <summary>
        /// PanelHolder control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Diten.Web.UI.WebControls.Panel PanelHolder;
        
        /// <summary>
        /// NorthPanel control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Diten.Web.UI.WebControls.Panel NorthPanel;
        
        /// <summary>
        /// WestPanel control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Diten.Web.UI.WebControls.Panel WestPanel;
        
        /// <summary>
        /// CenterPanel control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Diten.Web.UI.WebControls.Panel CenterPanel;
        
        /// <summary>
        /// Explorer control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Diten.Web.UI.WebControls.Explorer Explorer;
        
        /// <summary>
        /// EastPanel control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Diten.Web.UI.WebControls.Panel EastPanel;
        
        /// <summary>
        /// StatusForm control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Ext.Net.FormPanel StatusForm;
        
        /// <summary>
        /// SouthPanel control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Diten.Web.UI.WebControls.Panel SouthPanel;
        
        /// <summary>
        /// StatusBar control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Ext.Net.StatusBar StatusBar;
        
        /// <summary>
        /// wordCount control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Ext.Net.ToolbarTextItem wordCount;
        
        /// <summary>
        /// charCount control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Ext.Net.ToolbarTextItem charCount;
        
        /// <summary>
        /// clock control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Ext.Net.ToolbarTextItem clock;
        
        /// <summary>
        /// ButtonViewDetail control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Diten.Web.UI.WebControls.Button ButtonViewDetail;
        
        /// <summary>
        /// ButtonViewIcons control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Diten.Web.UI.WebControls.Button ButtonViewIcons;
    }
}
