//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Diten.Windows.Applications.Tools.Official.Bookmarks {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Diten.Windows.Applications.Tools.Official.Bookmarks.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        public static System.Drawing.Icon Chrome {
            get {
                object obj = ResourceManager.GetObject("Chrome", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bookmarks Menu.
        /// </summary>
        public static System.String Diten_Bookmarks_Menu {
            get {
                return ResourceManager.GetString("Diten_Bookmarks_Menu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        public static System.Drawing.Icon Firefox {
            get {
                object obj = ResourceManager.GetObject("Firefox", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        public static System.Drawing.Icon Folder {
            get {
                object obj = ResourceManager.GetObject("Folder", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        public static System.Drawing.Icon FolderOpen {
            get {
                object obj = ResourceManager.GetObject("FolderOpen", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        public static System.Drawing.Icon Opera {
            get {
                object obj = ResourceManager.GetObject("Opera", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ADD_DATE.
        /// </summary>
        public static System.String PropADD_DATE {
            get {
                return ResourceManager.GetString("PropADD_DATE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HREF.
        /// </summary>
        public static System.String PropHREF {
            get {
                return ResourceManager.GetString("PropHREF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ICON.
        /// </summary>
        public static System.String PropICON {
            get {
                return ResourceManager.GetString("PropICON", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ICON_URI.
        /// </summary>
        public static System.String PropICON_URI {
            get {
                return ResourceManager.GetString("PropICON_URI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LAST_MODIFIED.
        /// </summary>
        public static System.String PropLAST_MODIFIED {
            get {
                return ResourceManager.GetString("PropLAST_MODIFIED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SHORTCUTURL.
        /// </summary>
        public static System.String PropSHORTCUTURL {
            get {
                return ResourceManager.GetString("PropSHORTCUTURL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TAGS.
        /// </summary>
        public static System.String PropTAGS {
            get {
                return ResourceManager.GetString("PropTAGS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A.
        /// </summary>
        public static System.String TagA {
            get {
                return ResourceManager.GetString("TagA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to #comment.
        /// </summary>
        public static System.String TagComment {
            get {
                return ResourceManager.GetString("TagComment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DL.
        /// </summary>
        public static System.String TagDL {
            get {
                return ResourceManager.GetString("TagDL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DOCTYPE.
        /// </summary>
        public static System.String TagDOCTYPE {
            get {
                return ResourceManager.GetString("TagDOCTYPE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DT.
        /// </summary>
        public static System.String TagDT {
            get {
                return ResourceManager.GetString("TagDT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to H1.
        /// </summary>
        public static System.String TagH1 {
            get {
                return ResourceManager.GetString("TagH1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to H3.
        /// </summary>
        public static System.String TagH3 {
            get {
                return ResourceManager.GetString("TagH3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to META.
        /// </summary>
        public static System.String TagMETA {
            get {
                return ResourceManager.GetString("TagMETA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to p.
        /// </summary>
        public static System.String TagP {
            get {
                return ResourceManager.GetString("TagP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TITLE.
        /// </summary>
        public static System.String TagTITLE {
            get {
                return ResourceManager.GetString("TagTITLE", resourceCulture);
            }
        }
    }
}
