//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Diten.Parameters {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "16.2.0.0")]
    public sealed partial class Constants : global::System.Configuration.ApplicationSettingsBase {
        
        private static Constants defaultInstance = ((Constants)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Constants())));
        
        public static Constants Default {
            get {
                return defaultInstance;
            }
        }
        
        /// <summary>
        /// Include [!@#$%]
        /// </summary>
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Configuration.SettingsDescriptionAttribute("Include [!@#$%]")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("!@#$%")]
        public string InjectionCharactersGroup01 {
            get {
                return ((string)(this["InjectionCharactersGroup01"]));
            }
        }
        
        /// <summary>
        /// Include [^&amp;*()-=_+~`]
        /// </summary>
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Configuration.SettingsDescriptionAttribute("Include [^&*()-=_+~`]")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("^&*()-=_+~`")]
        public string InjectionCharactersGroup02 {
            get {
                return ((string)(this["InjectionCharactersGroup02"]));
            }
        }
        
        /// <summary>
        /// Include [{}[]:&quot;;&apos;&lt;&gt;,.?/&apos;\]
        /// </summary>
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Configuration.SettingsDescriptionAttribute("Include [{}[]:\";\'<>,.?/\'\\]")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("{}[]:\";\'<>,.?/\'\\")]
        public string InjectionCharactersGroup03 {
            get {
                return ((string)(this["InjectionCharactersGroup03"]));
            }
        }
        
        /// <summary>
        /// Include [ABCDEF1234567890]
        /// </summary>
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Configuration.SettingsDescriptionAttribute("Include [ABCDEF1234567890]")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("ABCDEF1234567890")]
        public string HexCharacters {
            get {
                return ((string)(this["HexCharacters"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Persian (Iran)")]
        public string PersianCultureDisplayName {
            get {
                return ((string)(this["PersianCultureDisplayName"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("sys-sys")]
        public string CultureName {
            get {
                return ((string)(this["CultureName"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("...")]
        public string MaskDots {
            get {
                return ((string)(this["MaskDots"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("DITeN.Net")]
        public string DomainName {
            get {
                return ((string)(this["DomainName"]));
            }
        }
        
        /// <summary>
        /// Default port is [101100]
        /// </summary>
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Configuration.SettingsDescriptionAttribute("Default port is [101100]")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("101100")]
        public int ClientTalkingServicePort {
            get {
                return ((int)(this["ClientTalkingServicePort"]));
            }
        }
        
        /// <summary>
        /// Default port is [101101]
        /// </summary>
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Configuration.SettingsDescriptionAttribute("Default port is [101101]")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("101101")]
        public int ClientListeningServicePort {
            get {
                return ((int)(this["ClientListeningServicePort"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("9964D1A2B3FA4A3E9D5AB132576902831343AAE978BD42D7918A4B5D6F64C05B")]
        public string Password {
            get {
                return ((string)(this["Password"]));
            }
        }
        
        /// <summary>
        /// localhost [127.0.0.1]
        /// </summary>
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Configuration.SettingsDescriptionAttribute("localhost [127.0.0.1]")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("127.0.0.1")]
        public string LocalIp {
            get {
                return ((string)(this["LocalIp"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("DITeN Framework")]
        public string DITeNFramework {
            get {
                return ((string)(this["DITeNFramework"]));
            }
        }
        
        /// <summary>
        /// Value is [DTI]
        /// </summary>
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Configuration.SettingsDescriptionAttribute("Value is [DTI]")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("DTI")]
        public string TempFolderItemExtention {
            get {
                return ((string)(this["TempFolderItemExtention"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("manifest")]
        public string ManifestFileExtention {
            get {
                return ((string)(this["ManifestFileExtention"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Initialize")]
        public string InitializeMethodName {
            get {
                return ((string)(this["InitializeMethodName"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("▒")]
        public string Separator {
            get {
                return ((string)(this["Separator"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Diten\\Cloud")]
        public string CloudAppPhysicalPath {
            get {
                return ((string)(this["CloudAppPhysicalPath"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("bin")]
        public string BinFolder {
            get {
                return ((string)(this["BinFolder"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("config")]
        public string ConfigFileExtention {
            get {
                return ((string)(this["ConfigFileExtention"]));
            }
        }
        
        /// <summary>
        /// Value is [HTTP_X_FORWARDED_FOR]
        /// </summary>
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Configuration.SettingsDescriptionAttribute("Value is [HTTP_X_FORWARDED_FOR]")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("HTTP_X_FORWARDED_FOR")]
        public string ServerVariables000 {
            get {
                return ((string)(this["ServerVariables000"]));
            }
        }
        
        /// <summary>
        /// Value is [REMOTE_ADDR]
        /// </summary>
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Configuration.SettingsDescriptionAttribute("Value is [REMOTE_ADDR]")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("REMOTE_ADDR")]
        public string ServerVariables001 {
            get {
                return ((string)(this["ServerVariables001"]));
            }
        }
    }
}
