//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Diten.Parameters {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "16.3.0.0")]
    public sealed partial class Exceptions : global::System.Configuration.ApplicationSettingsBase {
        
        private static Exceptions defaultInstance = ((Exceptions)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Exceptions())));
        
        public static Exceptions Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("ApplicationModule must have one application. Please set Application property.")]
        public string ApplicationModule_Application_ArgumentNullException {
            get {
                return ((System.String)(this["ApplicationModule_Application_ArgumentNullException"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("There is no application assigned to this module. Application property can not be " +
            "null.")]
        public string ApplicationModule_Initialize_NullReferenceException {
            get {
                return ((System.String)(this["ApplicationModule_Initialize_NullReferenceException"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Application name cannot be null.")]
        public string Diten_Web_UI_Application_ApplicationName_Message {
            get {
                return ((System.String)(this["Diten_Web_UI_Application_ApplicationName_Message"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("ApplicationName")]
        public string Diten_Web_UI_Application_ApplicationName_ParamName {
            get {
                return ((System.String)(this["Diten_Web_UI_Application_ApplicationName_ParamName"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Base type is null. This component is not inherited form an object.")]
        public string Diten_Web_UI_WebControls_Button_XType {
            get {
                return ((System.String)(this["Diten_Web_UI_WebControls_Button_XType"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Key [{0}] not found.")]
        public string Diten_Variables_GetConfig_ArgumentException_KeyNotFound {
            get {
                return ((System.String)(this["Diten_Variables_GetConfig_ArgumentException_KeyNotFound"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Value of key [{0}] is null.")]
        public string Diten_Variables_GetConfig_ArgumentException_ValueNotFound {
            get {
                return ((System.String)(this["Diten_Variables_GetConfig_ArgumentException_ValueNotFound"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Resource not found in [{}].")]
        public string Diten_Web_ResourceProvider_GetFile {
            get {
                return ((System.String)(this["Diten_Web_ResourceProvider_GetFile"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Parameter [value] must be a hexadecimal string.")]
        public string Diten_ExtensionMethods_ExString_ToString_Hexadecimal {
            get {
                return ((System.String)(this["Diten_ExtensionMethods_ExString_ToString_Hexadecimal"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("A string can not contains [{0}] (UnsafeStringTag) in diten framework.")]
        public string Diten_ExtensionMethods_ExString_ToSafeString {
            get {
                return ((System.String)(this["Diten_ExtensionMethods_ExString_ToSafeString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("The object of type [{0}] is not a [{1}] object.")]
        public string Diten_Numeric_Number_CompareTo_PObject {
            get {
                return ((System.String)(this["Diten_Numeric_Number_CompareTo_PObject"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("DITeN Debug Message")]
        public string DebugMessage {
            get {
                return ((System.String)(this["DebugMessage"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("There is no frame in StackTrace.")]
        public string Diten_Exception_Exception {
            get {
                return ((System.String)(this["Diten_Exception_Exception"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("There is no EOF tag inside of value property.")]
        public string DIten_NoEOFTagInValue {
            get {
                return ((System.String)(this["DIten_NoEOFTagInValue"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Invalid cast from [{0}] to [{1}].")]
        public string InvalidCast_FromTo {
            get {
                return ((System.String)(this["InvalidCast_FromTo"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Invalid cast to [DBNull]")]
        public string InvalidCast_DBNull {
            get {
                return ((System.String)(this["InvalidCast_DBNull"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Invalid cast to [Empty]")]
        public string InvalidCast_Empty {
            get {
                return ((System.String)(this["InvalidCast_Empty"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string Argument_InvalidTypeWithPointersNotSupported {
            get {
                return ((System.String)(this["Argument_InvalidTypeWithPointersNotSupported"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string Argument_DestinationTooShort {
            get {
                return ((System.String)(this["Argument_DestinationTooShort"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string Argument_OverlapAlignmentMismatch {
            get {
                return ((System.String)(this["Argument_OverlapAlignmentMismatch"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("fg")]
        public string NotSupported_Type {
            get {
                return ((System.String)(this["NotSupported_Type"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string Argument_CannotExtractScalar {
            get {
                return ((System.String)(this["Argument_CannotExtractScalar"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string ArgumentOutOfRange_Index {
            get {
                return ((System.String)(this["ArgumentOutOfRange_Index"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string ArgumentOutOfRange_NeedNonNegNum {
            get {
                return ((System.String)(this["ArgumentOutOfRange_NeedNonNegNum"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string ArgumentOutOfRange_Count {
            get {
                return ((System.String)(this["ArgumentOutOfRange_Count"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string Argument_AddingDuplicateWithKey {
            get {
                return ((System.String)(this["Argument_AddingDuplicateWithKey"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string InvalidOperation_EnumFailedVersion {
            get {
                return ((System.String)(this["InvalidOperation_EnumFailedVersion"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string InvalidOperation_EnumOpCantHappen {
            get {
                return ((System.String)(this["InvalidOperation_EnumOpCantHappen"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string InvalidOperation_NoValue {
            get {
                return ((System.String)(this["InvalidOperation_NoValue"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string InvalidOperation_ConcurrentOperationsNotSupported {
            get {
                return ((System.String)(this["InvalidOperation_ConcurrentOperationsNotSupported"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string InvalidOperation_HandleIsNotInitialized {
            get {
                return ((System.String)(this["InvalidOperation_HandleIsNotInitialized"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string InvalidOperation_HandleIsNotPinned {
            get {
                return ((System.String)(this["InvalidOperation_HandleIsNotPinned"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string Argument_BadFormatSpecifier {
            get {
                return ((System.String)(this["Argument_BadFormatSpecifier"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string Argument_PrecisionTooLarge {
            get {
                return ((System.String)(this["Argument_PrecisionTooLarge"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string Argument_InvalidOffLen {
            get {
                return ((System.String)(this["Argument_InvalidOffLen"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string Arg_WrongType {
            get {
                return ((System.String)(this["Arg_WrongType"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string Arg_KeyNotFoundWithKey {
            get {
                return ((System.String)(this["Arg_KeyNotFoundWithKey"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string InvalidOperation_EnumNotStarted {
            get {
                return ((System.String)(this["InvalidOperation_EnumNotStarted"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string InvalidOperation_EnumEnded {
            get {
                return ((System.String)(this["InvalidOperation_EnumEnded"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string Arg_TypeNotSupported {
            get {
                return ((System.String)(this["Arg_TypeNotSupported"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string ArgumentOutOfRange_IndexCount {
            get {
                return ((System.String)(this["ArgumentOutOfRange_IndexCount"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string ArgumentOutOfRange_IndexCountBuffer {
            get {
                return ((System.String)(this["ArgumentOutOfRange_IndexCountBuffer"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string Arg_ArrayPlusOffTooSmall {
            get {
                return ((System.String)(this["Arg_ArrayPlusOffTooSmall"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string NotSupported_ReadOnlyCollection {
            get {
                return ((System.String)(this["NotSupported_ReadOnlyCollection"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string Arg_RankMultiDimNotSupported {
            get {
                return ((System.String)(this["Arg_RankMultiDimNotSupported"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string Arg_NonZeroLowerBound {
            get {
                return ((System.String)(this["Arg_NonZeroLowerBound"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string ArgumentOutOfRange_ListInsert {
            get {
                return ((System.String)(this["ArgumentOutOfRange_ListInsert"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string ArgumentOutOfRange_SmallCapacity {
            get {
                return ((System.String)(this["ArgumentOutOfRange_SmallCapacity"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string ArgumentOutOfRange_BiggerThanCollection {
            get {
                return ((System.String)(this["ArgumentOutOfRange_BiggerThanCollection"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string Serialization_MissingKeys {
            get {
                return ((System.String)(this["Serialization_MissingKeys"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string Serialization_NullKey {
            get {
                return ((System.String)(this["Serialization_NullKey"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string NotSupported_KeyCollectionSet {
            get {
                return ((System.String)(this["NotSupported_KeyCollectionSet"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string NotSupported_ValueCollectionSet {
            get {
                return ((System.String)(this["NotSupported_ValueCollectionSet"]));
            }
        }
        
        /// <summary>
        /// drth
        /// </summary>
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Configuration.SettingsDescriptionAttribute("drth")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string InvalidOperation_NullArray {
            get {
                return ((System.String)(this["InvalidOperation_NullArray"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string TaskT_TransitionToFinal_AlreadyCompleted {
            get {
                return ((System.String)(this["TaskT_TransitionToFinal_AlreadyCompleted"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string TaskCompletionSourceT_TrySetException_NullException {
            get {
                return ((System.String)(this["TaskCompletionSourceT_TrySetException_NullException"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string TaskCompletionSourceT_TrySetException_NoExceptions {
            get {
                return ((System.String)(this["TaskCompletionSourceT_TrySetException_NoExceptions"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string NotSupported_StringComparison {
            get {
                return ((System.String)(this["NotSupported_StringComparison"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string ConcurrentCollection_SyncRoot_NotSupported {
            get {
                return ((System.String)(this["ConcurrentCollection_SyncRoot_NotSupported"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string Task_MultiTaskContinuation_NullTask {
            get {
                return ((System.String)(this["Task_MultiTaskContinuation_NullTask"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string Task_MultiTaskContinuation_EmptyTaskList {
            get {
                return ((System.String)(this["Task_MultiTaskContinuation_EmptyTaskList"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string Task_Start_TaskCompleted {
            get {
                return ((System.String)(this["Task_Start_TaskCompleted"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string InvalidOperation_WrongAsyncResultOrEndCalledMultiple {
            get {
                return ((System.String)(this["InvalidOperation_WrongAsyncResultOrEndCalledMultiple"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string Task_Start_Promise {
            get {
                return ((System.String)(this["Task_Start_Promise"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string Task_Start_ContinuationTask {
            get {
                return ((System.String)(this["Task_Start_ContinuationTask"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string Task_Start_AlreadyStarted {
            get {
                return ((System.String)(this["Task_Start_AlreadyStarted"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string Task_RunSynchronously_Continuation {
            get {
                return ((System.String)(this["Task_RunSynchronously_Continuation"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string Task_RunSynchronously_Promise {
            get {
                return ((System.String)(this["Task_RunSynchronously_Promise"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string Task_RunSynchronously_TaskCompleted {
            get {
                return ((System.String)(this["Task_RunSynchronously_TaskCompleted"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string Task_RunSynchronously_AlreadyStarted {
            get {
                return ((System.String)(this["Task_RunSynchronously_AlreadyStarted"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string AsyncMethodBuilder_InstanceNotInitialized {
            get {
                return ((System.String)(this["AsyncMethodBuilder_InstanceNotInitialized"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string Task_ContinueWith_ESandLR {
            get {
                return ((System.String)(this["Task_ContinueWith_ESandLR"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string Task_ContinueWith_NotOnAnything {
            get {
                return ((System.String)(this["Task_ContinueWith_NotOnAnything"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string Task_Delay_InvalidDelay {
            get {
                return ((System.String)(this["Task_Delay_InvalidDelay"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string Task_Delay_InvalidMillisecondsDelay {
            get {
                return ((System.String)(this["Task_Delay_InvalidMillisecondsDelay"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string Task_Dispose_NotCompleted {
            get {
                return ((System.String)(this["Task_Dispose_NotCompleted"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string Task_ThrowIfDisposed {
            get {
                return ((System.String)(this["Task_ThrowIfDisposed"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string Task_WaitMulti_NullTask {
            get {
                return ((System.String)(this["Task_WaitMulti_NullTask"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string ArgumentException_OtherNotArrayOfCorrectLength {
            get {
                return ((System.String)(this["ArgumentException_OtherNotArrayOfCorrectLength"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string ArgumentNull_Array {
            get {
                return ((System.String)(this["ArgumentNull_Array"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string ArgumentNull_SafeHandle {
            get {
                return ((System.String)(this["ArgumentNull_SafeHandle"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string ArgumentOutOfRange_EndIndexStartIndex {
            get {
                return ((System.String)(this["ArgumentOutOfRange_EndIndexStartIndex"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string ArgumentOutOfRange_Enum {
            get {
                return ((System.String)(this["ArgumentOutOfRange_Enum"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string ArgumentOutOfRange_HugeArrayNotSupported {
            get {
                return ((System.String)(this["ArgumentOutOfRange_HugeArrayNotSupported"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string Argument_AddingDuplicate {
            get {
                return ((System.String)(this["Argument_AddingDuplicate"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string Argument_InvalidArgumentForComparison {
            get {
                return ((System.String)(this["Argument_InvalidArgumentForComparison"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string Arg_LowerBoundsMustMatch {
            get {
                return ((System.String)(this["Arg_LowerBoundsMustMatch"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string Arg_MustBeType {
            get {
                return ((System.String)(this["Arg_MustBeType"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string Arg_Need1DArray {
            get {
                return ((System.String)(this["Arg_Need1DArray"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string Arg_NeedAtLeast1Rank {
            get {
                return ((System.String)(this["Arg_NeedAtLeast1Rank"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string Arg_Need2DArray {
            get {
                return ((System.String)(this["Arg_Need2DArray"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string Arg_Need3DArray {
            get {
                return ((System.String)(this["Arg_Need3DArray"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string Arg_RankIndices {
            get {
                return ((System.String)(this["Arg_RankIndices"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string Arg_RanksAndBounds {
            get {
                return ((System.String)(this["Arg_RanksAndBounds"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string InvalidOperation_IComparerFailed {
            get {
                return ((System.String)(this["InvalidOperation_IComparerFailed"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string NotSupported_FixedSizeCollection {
            get {
                return ((System.String)(this["NotSupported_FixedSizeCollection"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string Rank_MultiDimNotSupported {
            get {
                return ((System.String)(this["Rank_MultiDimNotSupported"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("The length of {0} must be the same.")]
        public string Diten_SameLenght {
            get {
                return ((System.String)(this["Diten_SameLenght"]));
            }
        }
        
        /// <summary>
        /// {0} cannot be of type [type name: {1} | type :{2)}]
        /// </summary>
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Configuration.SettingsDescriptionAttribute("{0} cannot be of type [type name: {1} | type :{2)}]")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("{0} cannot be of type [type name: {1} | type :{2)}]")]
        public string Diten_TypeException {
            get {
                return ((System.String)(this["Diten_TypeException"]));
            }
        }
    }
}
