//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Diten.Parameters {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "16.2.0.0")]
    public sealed partial class System : global::System.Configuration.ApplicationSettingsBase {
        
        private static System defaultInstance = ((System)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new System())));
        
        public static System Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("DTDBOUSR001")]
        public string DBOwnerUser {
            get {
                return ((string)(this["DBOwnerUser"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("kdcsvDELwRyUgZNkpGLgfN46GPX2v26pT9MhRj1gMLhnepCpUVhCWBt4FsGmUF04dcas2ewPF1mcuWuvj" +
            "efsJFpkAD9CRrJUF7Jc")]
        public string DBOwnerPassword {
            get {
                return ((string)(this["DBOwnerPassword"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("DTDBAUSR001")]
        public string DBAdminUser {
            get {
                return ((string)(this["DBAdminUser"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("3pvC6MK7kzn2WgRY61lWZcAystyZaJEIov0hZnpNWQ7CqBhXPOgLWsxo0ULsK5qtAtJzLQHAOlv2Ge2aw" +
            "acdGmW0DQpxRGOIfUKD")]
        public string DBAdminPassword {
            get {
                return ((string)(this["DBAdminPassword"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("get_")]
        public string GetFrameFunctionExtention {
            get {
                return ((string)(this["GetFrameFunctionExtention"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("set_")]
        public string SetFrameFunctionExtention {
            get {
                return ((string)(this["SetFrameFunctionExtention"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("*.dll")]
        public string AllDLLFiles {
            get {
                return ((string)(this["AllDLLFiles"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Win32_")]
        public string Win32Extention {
            get {
                return ((string)(this["Win32Extention"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("mongodb://")]
        public string MongoDBProtocolExtention {
            get {
                return ((string)(this["MongoDBProtocolExtention"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("32768")]
        public int MaxUrlLength {
            get {
                return ((int)(this["MaxUrlLength"]));
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("DITeN Server")]
        public string DefaultMailDisplayName {
            get {
                return ((string)(this["DefaultMailDisplayName"]));
            }
            set {
                this["DefaultMailDisplayName"] = value;
            }
        }
    }
}
