//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace Diten.Web.UI.Apps.Templates {
    
    
    public partial class Test {
        
        /// <summary>
        /// PanelContent control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Diten.Web.UI.WebControls.ContentPanel PanelContent;
        
        /// <summary>
        /// P1 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Diten.Web.UI.WebControls.Panel P1;
        
        /// <summary>
        /// SearchTextField control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Diten.Web.UI.WebControls.SearchTextField SearchTextField;
        
        /// <summary>
        /// P2 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Diten.Web.UI.WebControls.Panel P2;
        
        /// <summary>
        /// P3 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Diten.Web.UI.WebControls.Panel P3;
        
        /// <summary>
        /// P4 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Diten.Web.UI.WebControls.Panel P4;
    }
}
