//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Diten.Net.Mail {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class MailResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal MailResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Diten.Net.Mail.MailResources", typeof(MailResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Baa salaam^
        ///^
        ///Lotfan jahate faeaal saazie hesaabe kaarbarie khod dar daamenh %DomainName% bar rooye linke zir click namaaeid.^
        ///^
        ///%JoinDomain%^
        ///^
        ///baa tashakor^
        ///%SystemDomain%.
        /// </summary>
        public static string ActivateUserAccount {
            get {
                return ResourceManager.GetString("ActivateUserAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Baa salaam^
        ///^
        ///Peyroye darkhaaste shoma linke tanzime mojadade kalameh oboor baray shoma ersaal shod. lotfan jahate tanzime mojadade kalameh oboor bar rooy linke zir click namaeid. Agar in darkhaast raa shoma nakardeheid lazem be anjaame kaari nist va tey 10 daghighe digar in link be soorate otomaatic laghv khaahad shod. Shoma 10 daghighe jahat estefaadeh az in link va taghire kalameh oboor khod vaght daarid.^
        ///^
        ///^
        ///%ChangePasswordLink%^
        ///^
        ///^
        ///baa tashakor^
        ///%SystemDomain%.
        /// </summary>
        public static string ChangePassword {
            get {
                return ResourceManager.GetString("ChangePassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Baa salaam^
        ///^
        ///ehteraaman be estehzaar miresaanad kaarbar %FullName% baa hesaabe kaarbarie %UserName% darkhaaste peyvastan be daameneh %DomainName% raa darad. ayaa baa peyvastane vey be in daamaneh movafeghid?^
        ///^
        ///%Agree%    %Disagree%^
        ///^
        ///baa tashakor^
        ///%SystemDomain%.
        /// </summary>
        public static string DomainJoinAdminAgreement {
            get {
                return ResourceManager.GetString("DomainJoinAdminAgreement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Baa salaam^
        ///^
        ///zemne tabrik baraye peyvastan be daamaneh %DomainName% lotfan jahate takmil faraayande sabte naam va faeaal saazie hesaabe kaarbarie khod bar rooy linke zir click namaaeid.^
        ///^
        ///%JoinDomain%^
        ///^
        ///baa tashakor^
        ///%SystemDomain%.
        /// </summary>
        public static string DomainJoinUserAgreement {
            get {
                return ResourceManager.GetString("DomainJoinUserAgreement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Baa salaam^
        ///^
        ///Modire daamaneh %DomainName% baraaye shoma yek hesaab kaarbari ijaad kardeh ke moshakhasaat aan dar zir aavardeh shodeh. Lotfan jahate faeaal saazie aan bar rooye linke zir click namaaeid.^
        ///^
        ///^
        ///Naame kaarbari %UserName%^
        ///Kalameh oboor %Password%^
        ///^
        ///%JoinDomain%^
        ///^
        ///baa tashakor^
        ///%SystemDomain%.
        /// </summary>
        public static string NewUser {
            get {
                return ResourceManager.GetString("NewUser", resourceCulture);
            }
        }
    }
}
