//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace Diten.Web.UI.Apps.Stats {
    
    
    public partial class StatsCenterPanel {
        
        /// <summary>
        /// ContentPanel control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Diten.Web.UI.WebControls.Panel ContentPanel;
        
        /// <summary>
        /// TabPanelMain control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Diten.Web.UI.WebControls.TabPanel TabPanelMain;
        
        /// <summary>
        /// PanelWebStats control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Diten.Web.UI.WebControls.Panel PanelWebStats;
        
        /// <summary>
        /// TabPanelWebSites control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Diten.Web.UI.WebControls.TabPanel TabPanelWebSites;
    }
}
